# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Home
email: zrmacc@gmail.com
# description: >-
# baseurl: "zrmacc.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Plugins
plugins: 
  - jekyll-include-cache

# theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.17.2"

# Include pages
include: ["_pages"]

# Allow searching
search: true

# Author
author:
  name: "Zachary R. McCaw"
  bio: "Ph.D. in Biostatistics"
  location: "Mountain View, CA"
  avatar: "/assets/images/Avatar.jpeg"
  links:
    - label: "CV"
      icon: "fas fa-file-alt"
      url: "/CV/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:zmccaw@alumni.harvard.edu"
    - label: "Github"
      icon: "fab fa-github-square"
      url: "https://github.com/zrmacc"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/zachary-mccaw-16638b39/"
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0002-2006-9828"

# Collections
collections:
  statistics:
    output: true 
    permalink: /Collections/Statistics/:name
  eventtimes:
    output: true
    permalink: /Collections/Eventtimes/:name

collections_dir: collections

# Categories
categories: [Asymptotics, Implementation, Inference, Mathematical, Methods, Stochastic]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
